Merge: (#12) JWT 세팅
Survival-From-Epidemic/Survival-From-Epidemic-Backend pull request #13
Opened 2023-10-05 11:31 UTC by KMS06

## 작업 내용 설명
- [ ]  프로젝트의 전체적인 jwt 세팅

<br/>

## 주요 변경 사항
-  jwt 관련 파일 생성

<br/>

## 결과물

<br/>

## 관련 이슈
- resolved #

2023-10-05 14:05 UTC, alsdl0629 requested changes

2023-10-05 14:05 UTC, alsdl0629 commented on src/main/kotlin/team/sfe/server/global/security/exception/SecurityExceptions.kt
> +}
p1; object로 따로 빼지 말고 message를 직접 넣어주세요.
ex) https://github.com/Survival-From-Epidemic/Survival-From-Epidemic-Backend/blob/main/src/main/kotlin/team/sfe/server/global/exception/GlobalExceptions.kt

2023-10-05 14:05 UTC, alsdl0629 commented on src/main/kotlin/team/sfe/server/domain/user/domain/type/Authority.kt
> +    WRITER,
p1; WRITER는 빼주세요

2023-10-05 14:05 UTC, alsdl0629 commented on src/main/kotlin/team/sfe/server/global/security/jwt/JwtParser.kt
> +    private fun getClaims(token: String): Jws<Claims> {
p1; 한 칸 띄워주세요

2023-10-05 14:05 UTC, alsdl0629 commented on src/main/kotlin/team/sfe/server/global/security/jwt/JwtProperties.kt
> +}
p1; @EnableConfigurationProperties을 해당 클래스에 붙이면 다른 곳에서 빈 주입을 못받는 걸로 알고있습니다.
@EnableConfigurationProperties을 메인 클래스에 적용하거나 
@ConfigurationPropertiesScan을 사용해 빈 등록을 하는 방법이 있습니다.
개인적으로 
```kotlin
@Configuration
@ConfigurationPropertiesScan("team.sfe.server")
class ConfigurationPropertiesConfig
```
config파일을 따로 만들어서 등록하는 게 좋을 것 같습니다.

2023-10-05 14:06 UTC, alsdl0629 commented
pr 날리기 전에 프로젝트 실행되는지 확인해주세요!

2023-10-05 23:24 UTC, alsdl0629 requested changes

2023-10-05 23:24 UTC, alsdl0629 commented on src/main/kotlin/team/sfe/server/global/security/jwt/ConfigurationPropertiesConfig.kt
> +@Configuration
p1; @ConfigurationPropertiesScan으로 빈등록이 되서 @Configuration 없어도 될거같습니다

2023-10-05 23:24 UTC, alsdl0629 commented on src/main/kotlin/team/sfe/server/global/security/jwt/JwtProperties.kt
> +    var accessExp: Int = 0
p1; var 대신 val로 선언해서 불변으로 만들고, 여기서 초기화 안해줘도 될 것 같아요

2023-10-06 08:22 UTC, KMS06 commented on src/main/kotlin/team/sfe/server/global/security/jwt/JwtProperties.kt
> +    var accessExp: Int = 0
![image](https://github.com/Survival-From-Epidemic/Survival-From-Epidemic-Backend/assets/103491072/97a2b2d3-e53f-4c24-ae80-9c0909de7a33)
초기화 안하니 오류가 뜹니다

2023-10-06 10:16 UTC, alsdl0629 commented on src/main/kotlin/team/sfe/server/global/security/jwt/JwtProperties.kt
> +    var accessExp: Int = 0
혹시 @ConstructorBinding 사용하셨나요?

2023-10-07 15:45 UTC, alsdl0629 approved these changes
LGTM

2023-10-08 18:02 UTC, merged